# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Name of the company')),
                ('company_logo', models.CharField(max_length=255, verbose_name='URL of the company logo')),
                ('company_text', models.CharField(max_length=255, verbose_name='Some description of the company')),
                ('company_url', models.CharField(max_length=100, verbose_name='A url of the companys homepage')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=100, verbose_name='Name of the office')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='officecloud.Company')),
            ],
        ),
        migrations.CreateModel(
            name='OfficeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slackid', models.CharField(max_length=100, verbose_name='Slack ID')),
                ('offices', models.ManyToManyField(to='officecloud.Office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slack_url', models.CharField(max_length=100, verbose_name='Slack URL')),
                ('slack_apitoken', models.CharField(max_length=100, verbose_name='Slack Token')),
                ('slack_apisecret', models.CharField(max_length=100, verbose_name='Slack API Secret')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='company_slack',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='officecloud.Slack'),
        ),
    ]
