# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OfficeCloudToolsWeb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='OfficeUser',
        ),
    ]
