# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_name', models.CharField(max_length=255, verbose_name='Name of the attachment')),
                ('attachment_filename', models.CharField(max_length=255, verbose_name='Path of the attachment')),
                ('attachment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DebtStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
                ('status_desc', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Purchasing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchasing_name', models.CharField(max_length=100)),
                ('purchasing_date', models.DateField()),
                ('purchasing_value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='debt',
            name='debt_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kaffeekasse.DebtStatus'),
        ),
        migrations.AddField(
            model_name='debt',
            name='debt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
