# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kaffeekasse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_payer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitor', to=settings.AUTH_USER_MODEL),
        ),
    ]
