# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('officecloud', '0001_initial'),
        ('kaffeekasse', '0002_auto_20160404_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debt',
            name='debt_user',
        ),
        migrations.AddField(
            model_name='debt',
            name='debt_creditor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='debitor', to='officecloud.OfficeUser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt_payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor', to='officecloud.OfficeUser'),
        ),
    ]
