# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kaffeekasse', '0003_auto_20160404_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_value',
            field=models.FloatField(default=0, verbose_name='Value of this debt'),
            preserve_default=False,
        ),
    ]
